# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "wasm"
env.CARGO_TERM_COLOR = "always"

[jobs.wasm]
command = ["wasm-pack", "build", "--debug", "--target", "web"]
need_stdout = true
apply_gitignore = true
ignore = ["pkg/*"]
